name: deploy-to-home-server

on:
  push:
    branches:
      - "master"


jobs:
  docker-build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/node-web-app:latest

  deploy-docker:
    needs: docker-build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: SSH Remote Commands
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}

          script: |
            cd /home/allen/Documents/blog.zifengallen.me
            cat /home/allen/Documents/blog.zifengallen.me/sudoPwd.txt | sudo -S su
            cat /home/allen/Documents/blog.zifengallen.me/dockerPwd.txt | sudo docker login --username imballen --password-stdin

            cat /home/allen/Documents/blog.zifengallen.me/sudoPwd.txt | sudo -S docker stop devtest
            cat /home/allen/Documents/blog.zifengallen.me/sudoPwd.txt | sudo -S docker rm devtest
            cat /home/allen/Documents/blog.zifengallen.me/sudoPwd.txt | sudo -S docker pull imballen/node-web-app:latest
            cat /home/allen/Documents/blog.zifengallen.me/sudoPwd.txt | sudo -S docker run -p 4000:4000 -di  --name devtest --mount source=data_volume,target=/usr/src/app/config imballen/node-web-app:latest
            
         
            


